repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.7 # uv version
    hooks:
      - id: uv-lock
        name: Update uv.lock
  - repo: https://github.com/twisted/towncrier
    rev: 23.11.0 # run 'pre-commit autoupdate' to update
    hooks:
      - id: towncrier-check
      - id: towncrier-update
        files: $changelogs/
        args: ['--keep']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.4
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format
