services:
  app:
    container_name: vagas-app
    image: 'vagas-dev:${TAG-latest}'
    restart: always
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
  # ui:
  #   container_name: vagas-ui
  #   image: 'vagas-ui:${TAG-latest}'
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile
  #   depends_on:
  #     - app
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://vagas-app:8000
  #   ports:
  #     - "3000:3000"
  database:
    container_name: vagas-db
    image: postgres:18.4-alpine@sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  web:
    container_name: vagas-dev-web
    image: nginx:1.31.2-alpine@sha256:54f2a904c251d5a34adf545a72d32515a15e08418dae0266e23be2e18c66fefa
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    depends_on:
      - app
      # - ui
volumes:
  pgdata:
