services:
  app:
    restart: no
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - .venv
        - path: ./requirements.txt
          action: rebuild
  # ui:
  #   restart: no
  #   ports:
  #     - "3000:3000"
  database:
    restart: no
    ports:
      - "5432:5432"
  web:
    restart: no
