services:
  app:
    container_name: vagas-app
    image: 'vagas-dev:${TAG-latest}'
    restart: always
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
  # ui:
  #   container_name: vagas-ui
  #   image: 'vagas-ui:${TAG-latest}'
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile
  #   depends_on:
  #     - app
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://vagas-app:8000
  #   ports:
  #     - "3000:3000"
  database:
    container_name: vagas-db
    image: postgres:18.4-alpine@sha256:96d56f7f57c6aacd1fcb908bc83b345ec5f83231ee486dd66a1baadce274db88
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  web:
    container_name: vagas-dev-web
    image: nginx:1.31.3-alpine@sha256:4a73073bd557c65b759505da037898b61f1be6cbcc3c2c3aeac22d2a470c1752
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    depends_on:
      - app
      # - ui
volumes:
  pgdata:
