"""create discord_notified column on table jobs

Revision ID: 02e9dcf05ee9
Revises: ca947765ca3c
Create Date: 2026-03-03 05:59:17.345979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e9dcf05ee9'
down_revision: Union[str, Sequence[str], None] = 'ca947765ca3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('discord_notified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'discord_notified')
    # ### end Alembic commands ###
