"""create level column on table jobs

Revision ID: 6cccb8dedec7
Revises: 743ad74ddd17
Create Date: 2026-02-27 17:46:08.821673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cccb8dedec7'
down_revision: Union[str, Sequence[str], None] = '743ad74ddd17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('level', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'level')
    # ### end Alembic commands ###
