"""create telegram_notified column on table jobs

Revision ID: 72de72a7f13e
Revises: 6cccb8dedec7
Create Date: 2026-02-27 20:43:31.026246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72de72a7f13e'
down_revision: Union[str, Sequence[str], None] = '6cccb8dedec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('telegram_notified', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('jobs', 'notified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('notified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('jobs', 'telegram_notified')
    # ### end Alembic commands ###
