"""create keyword column on table jobs

Revision ID: a0aedd83b6f1
Revises: ba563ed5b8f1
Create Date: 2026-02-24 12:00:54.397122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0aedd83b6f1'
down_revision: Union[str, Sequence[str], None] = 'ba563ed5b8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('keyword', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'keyword')
    # ### end Alembic commands ###
