"""update columns of table jobs

Revision ID: ca947765ca3c
Revises: 72de72a7f13e
Create Date: 2026-03-02 00:04:19.351440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca947765ca3c'
down_revision: Union[str, Sequence[str], None] = '72de72a7f13e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'company',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('jobs', 'external_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'external_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('jobs', 'company',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
